### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/MI-000-SS00-000-css-intro-iMnt09#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://KatieMFritz.github.io/MI-000-SS00-000-css-intro-iMnt09/) and meets the following criteria:

- [x] Your project is built off [this base HTML and CSS](https://gist.github.com/chrisvfritz/279c36ab6e2301e8a35526be028d8a32) (you may modify both pages however you want, e.g. adding classes)
- [x] The website looks identical (or very close to) [this mockup](https://i.imgur.com/l2C8jTP.png) (make sure to zoom in on the image for actual sizes)
- [x] Any CSS selectors or properties may be used, though the project is possible using only what you saw in the lesson
- [x] No spacing HTML (e.g. `<br>`, `&amp;nbsp;`) is added to `index.html`

Is this what you were expecting? Look at my CSS and see if anything surprises you. I didn't change the base HTML.

**Comment by chrisvfritz** [comment]
@KatieMFritz The colors look great, but the sizes could use some quite a bit of work. Check out the Chrome extension I added to the sizes page for help. 🙂

**Comment by KatieMFritz** [comment]
@chrisvfritz Okay, look again to make sure?

**Comment by chrisvfritz** [comment]
Better, I think. I noticed your line height on `li` elements is drastically larger than the mockups and the `h2`s are also significantly bigger, but... good enough? 😅  :shipit:

**Comment by KatieMFritz** [comment]
Okay @chrisvfritz - take another look!

**Comment by chrisvfritz** [comment]
👍
